//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Controls/SubjectControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @SubjectControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @SubjectControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""SubjectControls"",
    ""maps"": [
        {
            ""name"": ""Subject"",
            ""id"": ""8dd9e2c8-9f44-4163-9fb7-c700731463f1"",
            ""actions"": [
                {
                    ""name"": ""Keyboard"",
                    ""type"": ""Button"",
                    ""id"": ""4bf9d622-b5dd-467b-ab81-7ac4235ade2f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""364e2eda-368f-413f-94db-7bdde7618625"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Keyboard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Subject
        m_Subject = asset.FindActionMap("Subject", throwIfNotFound: true);
        m_Subject_Keyboard = m_Subject.FindAction("Keyboard", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Subject
    private readonly InputActionMap m_Subject;
    private ISubjectActions m_SubjectActionsCallbackInterface;
    private readonly InputAction m_Subject_Keyboard;
    public struct SubjectActions
    {
        private @SubjectControls m_Wrapper;
        public SubjectActions(@SubjectControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Keyboard => m_Wrapper.m_Subject_Keyboard;
        public InputActionMap Get() { return m_Wrapper.m_Subject; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SubjectActions set) { return set.Get(); }
        public void SetCallbacks(ISubjectActions instance)
        {
            if (m_Wrapper.m_SubjectActionsCallbackInterface != null)
            {
                @Keyboard.started -= m_Wrapper.m_SubjectActionsCallbackInterface.OnKeyboard;
                @Keyboard.performed -= m_Wrapper.m_SubjectActionsCallbackInterface.OnKeyboard;
                @Keyboard.canceled -= m_Wrapper.m_SubjectActionsCallbackInterface.OnKeyboard;
            }
            m_Wrapper.m_SubjectActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Keyboard.started += instance.OnKeyboard;
                @Keyboard.performed += instance.OnKeyboard;
                @Keyboard.canceled += instance.OnKeyboard;
            }
        }
    }
    public SubjectActions @Subject => new SubjectActions(this);
    public interface ISubjectActions
    {
        void OnKeyboard(InputAction.CallbackContext context);
    }
}
